twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        image_helper: '@App\Service\ImageHelper'

when@test:
    twig:
        strict_variables: true
